-- CreateTable
CREATE TABLE `vod` (
    `vod_id` INTEGER NOT NULL AUTO_INCREMENT,
    `type_id` INTEGER NOT NULL,
    `group_id` INTEGER NOT NULL,
    `vod_name` VARCHAR(255) NOT NULL,
    `vod_sub` VARCHAR(255) NOT NULL,
    `vod_en` VARCHAR(255) NOT NULL,
    `vod_status` INTEGER NOT NULL,
    `vod_tag` VARCHAR(100) NOT NULL,
    `vod_class` VARCHAR(255) NOT NULL,
    `vod_pic` VARCHAR(1024) NOT NULL,
    `vod_pic_thumb` VARCHAR(1024) NOT NULL,
    `vod_pic_slide` VARCHAR(1024) NOT NULL,
    `vod_actor` VARCHAR(255) NOT NULL,
    `vod_director` VARCHAR(255) NOT NULL,
    `vod_writer` VARCHAR(100) NOT NULL,
    `vod_blurb` VARCHAR(255) NOT NULL,
    `vod_remarks` VARCHAR(100) NOT NULL,
    `vod_pubdate` VARCHAR(100) NOT NULL,
    `vod_total` INTEGER NOT NULL,
    `vod_serial` VARCHAR(20) NOT NULL,
    `vod_weekday` VARCHAR(30) NOT NULL,
    `vod_state` VARCHAR(30) NOT NULL,
    `vod_level` INTEGER NOT NULL,
    `vod_copyright` INTEGER NOT NULL,
    `vod_hits` INTEGER NOT NULL,
    `vod_hits_day` INTEGER NOT NULL,
    `vod_hits_week` INTEGER NOT NULL,
    `vod_hits_month` INTEGER NOT NULL,
    `vod_duration` VARCHAR(10) NOT NULL,
    `vod_time` INTEGER NOT NULL,
    `vod_time_add` INTEGER NOT NULL,
    `vod_douban_id` INTEGER NOT NULL,
    `vod_douban_score` DECIMAL(3, 1) NOT NULL,
    `vod_play_from` VARCHAR(255) NOT NULL,
    `vod_play_url` MEDIUMTEXT NOT NULL,

    PRIMARY KEY (`vod_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
