-- AlterTable
ALTER TABLE `vod` MODIFY `vod_name` VARCHAR(255) NULL,
    MODIFY `vod_sub` VARCHAR(255) NULL,
    MODIFY `vod_en` VARCHAR(255) NULL,
    MODIFY `vod_tag` VARCHAR(100) NULL,
    MODIFY `vod_class` VARCHAR(255) NULL,
    MODIFY `vod_pic` VARCHAR(1024) NULL,
    MODIFY `vod_pic_thumb` VARCHAR(1024) NULL,
    MODIFY `vod_pic_slide` VARCHAR(1024) NULL,
    MODIFY `vod_actor` VARCHAR(255) NULL,
    MODIFY `vod_director` VARCHAR(255) NULL,
    MODIFY `vod_writer` VARCHAR(100) NULL,
    MODIFY `vod_blurb` VARCHAR(255) NULL,
    MODIFY `vod_remarks` VARCHAR(100) NULL,
    MODIFY `vod_pubdate` VARCHAR(100) NULL,
    MODIFY `vod_state` VARCHAR(30) NULL,
    MODIFY `vod_level` INTEGER NULL,
    MODIFY `vod_copyright` INTEGER NULL DEFAULT 0,
    MODIFY `vod_hits` INTEGER NULL,
    MODIFY `vod_hits_day` INTEGER NULL,
    MODIFY `vod_hits_week` INTEGER NULL,
    MODIFY `vod_hits_month` INTEGER NULL,
    MODIFY `vod_duration` VARCHAR(10) NULL,
    MODIFY `vod_time` INTEGER NULL,
    MODIFY `vod_time_add` INTEGER NULL,
    MODIFY `vod_douban_id` INTEGER NULL,
    MODIFY `vod_douban_score` DECIMAL(3, 1) NULL,
    MODIFY `vod_play_from` VARCHAR(255) NULL,
    MODIFY `vod_play_url` MEDIUMTEXT NULL;
